services:
  landsealot-metadataform-python-webapp:
    ports:
      - 8501:8501
    container_name: landsealot-metadataform-python-webapp
    build: .
    volumes:
      - type: bind
        source: 
        target: /app/config.py
      - type: bind
        source: 
        target: /app/data
      - type: bind
        source: 
        target: /app/static
